// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `AppService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.maomao.server.manager.idl;

public interface _AppServiceOperations
{
    void stopServer(Ice.Current __current);

    java.util.List<App> loadApps(Ice.Current __current);

    String stopAppInstance(String appId, String instanceId, Ice.Current __current);

    String restartAppInstance(String appId, String instanceId, Ice.Current __current);

    String startAppInstance(String appId, String instanceId, Ice.Current __current);

    String removeAppInstance(String appId, String instanceId, Ice.Current __current);

    String createApp(String appId, Ice.Current __current);

    String removeApp(String appId, Ice.Current __current);

    String stopApp(String appId, Ice.Current __current);

    String startApp(String appId, Ice.Current __current);

    String restartApp(String appId, Ice.Current __current);

    String createAppInstance(String appId, String appInstanceJson, Ice.Current __current);

    String updateAppInstance(String appId, String instanceId, String appInstanceJson, Ice.Current __current);

    String syncServerInfo(Ice.Current __current);

    String getServerInfo(Ice.Current __current);

    String appSyncStatus(String jsonInfo, String ip, int port, Ice.Current __current);

    String appStopNotify(String appId, String ip, int port, Ice.Current __current);

    String appStartupNotify(String appId, String ip, int port, Ice.Current __current);

    void forceAppInstanceShutdown(int seconds, Ice.Current __current);

    void forceAppInstanceRestart(int seconds, Ice.Current __current);
}
