// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `AppService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.maomao.server.manager.idl;

public interface _AppServiceOperationsNC
{
    void stopServer();

    java.util.List<App> loadApps();

    String stopAppInstance(String appId, String instanceId);

    String restartAppInstance(String appId, String instanceId);

    String startAppInstance(String appId, String instanceId);

    String removeAppInstance(String appId, String instanceId);

    String createApp(String appId);

    String removeApp(String appId);

    String stopApp(String appId);

    String startApp(String appId);

    String restartApp(String appId);

    String createAppInstance(String appId, String appInstanceJson);

    String updateAppInstance(String appId, String instanceId, String appInstanceJson);

    String syncServerInfo();

    String getServerInfo();

    String appSyncStatus(String jsonInfo, String ip, int port);

    String appStopNotify(String appId, String ip, int port);

    String appStartupNotify(String appId, String ip, int port);

    void forceAppInstanceShutdown(int seconds);

    void forceAppInstanceRestart(int seconds);
}
