// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `SSHServerService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.maomao.server.manager.idl;

/**
 * App服务
 **/
public interface _SSHServerServiceOperations
{
    /**
     * 返回服务器信息
     * @param __current The Current object for the invocation.
     **/
    String loadServers(Ice.Current __current);

    /**
     * 添加一个服务器信息
     * @param __current The Current object for the invocation.
     **/
    String addServer(String serverJson, Ice.Current __current);

    /**
     * 更新一个服务器信息
     *
     * @param __current The Current object for the invocation.
     **/
    String updateServer(String key, String serverJson, Ice.Current __current);

    /**
     * 删除一个服务器信息
     * @param __current The Current object for the invocation.
     **/
    String removeServer(String key, Ice.Current __current);
}
