// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `AppService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.maomao.server.manager.idl;

public interface AppServicePrx extends Ice.ObjectPrx
{
    public void stopServer();

    public void stopServer(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_stopServer();

    public Ice.AsyncResult begin_stopServer(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_stopServer(Ice.Callback __cb);

    public Ice.AsyncResult begin_stopServer(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_stopServer(Callback_AppService_stopServer __cb);

    public Ice.AsyncResult begin_stopServer(java.util.Map<String, String> __ctx, Callback_AppService_stopServer __cb);

    public Ice.AsyncResult begin_stopServer(IceInternal.Functional_VoidCallback __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_stopServer(IceInternal.Functional_VoidCallback __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                            IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_stopServer(java.util.Map<String, String> __ctx, 
                                            IceInternal.Functional_VoidCallback __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_stopServer(java.util.Map<String, String> __ctx, 
                                            IceInternal.Functional_VoidCallback __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                            IceInternal.Functional_BoolCallback __sentCb);

    public void end_stopServer(Ice.AsyncResult __result);

    public java.util.List<App> loadApps();

    public java.util.List<App> loadApps(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_loadApps();

    public Ice.AsyncResult begin_loadApps(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_loadApps(Ice.Callback __cb);

    public Ice.AsyncResult begin_loadApps(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_loadApps(Callback_AppService_loadApps __cb);

    public Ice.AsyncResult begin_loadApps(java.util.Map<String, String> __ctx, Callback_AppService_loadApps __cb);

    public Ice.AsyncResult begin_loadApps(IceInternal.Functional_GenericCallback1<java.util.List<App>> __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_loadApps(IceInternal.Functional_GenericCallback1<java.util.List<App>> __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                          IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_loadApps(java.util.Map<String, String> __ctx, 
                                          IceInternal.Functional_GenericCallback1<java.util.List<App>> __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_loadApps(java.util.Map<String, String> __ctx, 
                                          IceInternal.Functional_GenericCallback1<java.util.List<App>> __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                          IceInternal.Functional_BoolCallback __sentCb);

    public java.util.List<App> end_loadApps(Ice.AsyncResult __result);

    public String stopAppInstance(String appId, String instanceId);

    public String stopAppInstance(String appId, String instanceId, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_stopAppInstance(String appId, String instanceId);

    public Ice.AsyncResult begin_stopAppInstance(String appId, String instanceId, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_stopAppInstance(String appId, String instanceId, Ice.Callback __cb);

    public Ice.AsyncResult begin_stopAppInstance(String appId, String instanceId, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_stopAppInstance(String appId, String instanceId, Callback_AppService_stopAppInstance __cb);

    public Ice.AsyncResult begin_stopAppInstance(String appId, String instanceId, java.util.Map<String, String> __ctx, Callback_AppService_stopAppInstance __cb);

    public Ice.AsyncResult begin_stopAppInstance(String appId, 
                                                 String instanceId, 
                                                 IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                 IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_stopAppInstance(String appId, 
                                                 String instanceId, 
                                                 IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                 IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                 IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_stopAppInstance(String appId, 
                                                 String instanceId, 
                                                 java.util.Map<String, String> __ctx, 
                                                 IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                 IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_stopAppInstance(String appId, 
                                                 String instanceId, 
                                                 java.util.Map<String, String> __ctx, 
                                                 IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                 IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                 IceInternal.Functional_BoolCallback __sentCb);

    public String end_stopAppInstance(Ice.AsyncResult __result);

    public String restartAppInstance(String appId, String instanceId);

    public String restartAppInstance(String appId, String instanceId, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_restartAppInstance(String appId, String instanceId);

    public Ice.AsyncResult begin_restartAppInstance(String appId, String instanceId, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_restartAppInstance(String appId, String instanceId, Ice.Callback __cb);

    public Ice.AsyncResult begin_restartAppInstance(String appId, String instanceId, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_restartAppInstance(String appId, String instanceId, Callback_AppService_restartAppInstance __cb);

    public Ice.AsyncResult begin_restartAppInstance(String appId, String instanceId, java.util.Map<String, String> __ctx, Callback_AppService_restartAppInstance __cb);

    public Ice.AsyncResult begin_restartAppInstance(String appId, 
                                                    String instanceId, 
                                                    IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                    IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_restartAppInstance(String appId, 
                                                    String instanceId, 
                                                    IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                    IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                    IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_restartAppInstance(String appId, 
                                                    String instanceId, 
                                                    java.util.Map<String, String> __ctx, 
                                                    IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                    IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_restartAppInstance(String appId, 
                                                    String instanceId, 
                                                    java.util.Map<String, String> __ctx, 
                                                    IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                    IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                    IceInternal.Functional_BoolCallback __sentCb);

    public String end_restartAppInstance(Ice.AsyncResult __result);

    public String startAppInstance(String appId, String instanceId);

    public String startAppInstance(String appId, String instanceId, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_startAppInstance(String appId, String instanceId);

    public Ice.AsyncResult begin_startAppInstance(String appId, String instanceId, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_startAppInstance(String appId, String instanceId, Ice.Callback __cb);

    public Ice.AsyncResult begin_startAppInstance(String appId, String instanceId, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_startAppInstance(String appId, String instanceId, Callback_AppService_startAppInstance __cb);

    public Ice.AsyncResult begin_startAppInstance(String appId, String instanceId, java.util.Map<String, String> __ctx, Callback_AppService_startAppInstance __cb);

    public Ice.AsyncResult begin_startAppInstance(String appId, 
                                                  String instanceId, 
                                                  IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_startAppInstance(String appId, 
                                                  String instanceId, 
                                                  IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                  IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_startAppInstance(String appId, 
                                                  String instanceId, 
                                                  java.util.Map<String, String> __ctx, 
                                                  IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_startAppInstance(String appId, 
                                                  String instanceId, 
                                                  java.util.Map<String, String> __ctx, 
                                                  IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                  IceInternal.Functional_BoolCallback __sentCb);

    public String end_startAppInstance(Ice.AsyncResult __result);

    public String removeAppInstance(String appId, String instanceId);

    public String removeAppInstance(String appId, String instanceId, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_removeAppInstance(String appId, String instanceId);

    public Ice.AsyncResult begin_removeAppInstance(String appId, String instanceId, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_removeAppInstance(String appId, String instanceId, Ice.Callback __cb);

    public Ice.AsyncResult begin_removeAppInstance(String appId, String instanceId, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_removeAppInstance(String appId, String instanceId, Callback_AppService_removeAppInstance __cb);

    public Ice.AsyncResult begin_removeAppInstance(String appId, String instanceId, java.util.Map<String, String> __ctx, Callback_AppService_removeAppInstance __cb);

    public Ice.AsyncResult begin_removeAppInstance(String appId, 
                                                   String instanceId, 
                                                   IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_removeAppInstance(String appId, 
                                                   String instanceId, 
                                                   IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                   IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_removeAppInstance(String appId, 
                                                   String instanceId, 
                                                   java.util.Map<String, String> __ctx, 
                                                   IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_removeAppInstance(String appId, 
                                                   String instanceId, 
                                                   java.util.Map<String, String> __ctx, 
                                                   IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                   IceInternal.Functional_BoolCallback __sentCb);

    public String end_removeAppInstance(Ice.AsyncResult __result);

    public String createApp(String appId);

    public String createApp(String appId, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_createApp(String appId);

    public Ice.AsyncResult begin_createApp(String appId, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_createApp(String appId, Ice.Callback __cb);

    public Ice.AsyncResult begin_createApp(String appId, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_createApp(String appId, Callback_AppService_createApp __cb);

    public Ice.AsyncResult begin_createApp(String appId, java.util.Map<String, String> __ctx, Callback_AppService_createApp __cb);

    public Ice.AsyncResult begin_createApp(String appId, 
                                           IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_createApp(String appId, 
                                           IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                           IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_createApp(String appId, 
                                           java.util.Map<String, String> __ctx, 
                                           IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_createApp(String appId, 
                                           java.util.Map<String, String> __ctx, 
                                           IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                           IceInternal.Functional_BoolCallback __sentCb);

    public String end_createApp(Ice.AsyncResult __result);

    public String removeApp(String appId);

    public String removeApp(String appId, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_removeApp(String appId);

    public Ice.AsyncResult begin_removeApp(String appId, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_removeApp(String appId, Ice.Callback __cb);

    public Ice.AsyncResult begin_removeApp(String appId, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_removeApp(String appId, Callback_AppService_removeApp __cb);

    public Ice.AsyncResult begin_removeApp(String appId, java.util.Map<String, String> __ctx, Callback_AppService_removeApp __cb);

    public Ice.AsyncResult begin_removeApp(String appId, 
                                           IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_removeApp(String appId, 
                                           IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                           IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_removeApp(String appId, 
                                           java.util.Map<String, String> __ctx, 
                                           IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_removeApp(String appId, 
                                           java.util.Map<String, String> __ctx, 
                                           IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                           IceInternal.Functional_BoolCallback __sentCb);

    public String end_removeApp(Ice.AsyncResult __result);

    public String stopApp(String appId);

    public String stopApp(String appId, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_stopApp(String appId);

    public Ice.AsyncResult begin_stopApp(String appId, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_stopApp(String appId, Ice.Callback __cb);

    public Ice.AsyncResult begin_stopApp(String appId, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_stopApp(String appId, Callback_AppService_stopApp __cb);

    public Ice.AsyncResult begin_stopApp(String appId, java.util.Map<String, String> __ctx, Callback_AppService_stopApp __cb);

    public Ice.AsyncResult begin_stopApp(String appId, 
                                         IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_stopApp(String appId, 
                                         IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_stopApp(String appId, 
                                         java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_stopApp(String appId, 
                                         java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb);

    public String end_stopApp(Ice.AsyncResult __result);

    public String startApp(String appId);

    public String startApp(String appId, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_startApp(String appId);

    public Ice.AsyncResult begin_startApp(String appId, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_startApp(String appId, Ice.Callback __cb);

    public Ice.AsyncResult begin_startApp(String appId, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_startApp(String appId, Callback_AppService_startApp __cb);

    public Ice.AsyncResult begin_startApp(String appId, java.util.Map<String, String> __ctx, Callback_AppService_startApp __cb);

    public Ice.AsyncResult begin_startApp(String appId, 
                                          IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_startApp(String appId, 
                                          IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                          IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_startApp(String appId, 
                                          java.util.Map<String, String> __ctx, 
                                          IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_startApp(String appId, 
                                          java.util.Map<String, String> __ctx, 
                                          IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                          IceInternal.Functional_BoolCallback __sentCb);

    public String end_startApp(Ice.AsyncResult __result);

    public String restartApp(String appId);

    public String restartApp(String appId, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_restartApp(String appId);

    public Ice.AsyncResult begin_restartApp(String appId, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_restartApp(String appId, Ice.Callback __cb);

    public Ice.AsyncResult begin_restartApp(String appId, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_restartApp(String appId, Callback_AppService_restartApp __cb);

    public Ice.AsyncResult begin_restartApp(String appId, java.util.Map<String, String> __ctx, Callback_AppService_restartApp __cb);

    public Ice.AsyncResult begin_restartApp(String appId, 
                                            IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_restartApp(String appId, 
                                            IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                            IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_restartApp(String appId, 
                                            java.util.Map<String, String> __ctx, 
                                            IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_restartApp(String appId, 
                                            java.util.Map<String, String> __ctx, 
                                            IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                            IceInternal.Functional_BoolCallback __sentCb);

    public String end_restartApp(Ice.AsyncResult __result);

    public String createAppInstance(String appId, String appInstanceJson);

    public String createAppInstance(String appId, String appInstanceJson, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_createAppInstance(String appId, String appInstanceJson);

    public Ice.AsyncResult begin_createAppInstance(String appId, String appInstanceJson, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_createAppInstance(String appId, String appInstanceJson, Ice.Callback __cb);

    public Ice.AsyncResult begin_createAppInstance(String appId, String appInstanceJson, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_createAppInstance(String appId, String appInstanceJson, Callback_AppService_createAppInstance __cb);

    public Ice.AsyncResult begin_createAppInstance(String appId, String appInstanceJson, java.util.Map<String, String> __ctx, Callback_AppService_createAppInstance __cb);

    public Ice.AsyncResult begin_createAppInstance(String appId, 
                                                   String appInstanceJson, 
                                                   IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_createAppInstance(String appId, 
                                                   String appInstanceJson, 
                                                   IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                   IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_createAppInstance(String appId, 
                                                   String appInstanceJson, 
                                                   java.util.Map<String, String> __ctx, 
                                                   IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_createAppInstance(String appId, 
                                                   String appInstanceJson, 
                                                   java.util.Map<String, String> __ctx, 
                                                   IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                   IceInternal.Functional_BoolCallback __sentCb);

    public String end_createAppInstance(Ice.AsyncResult __result);

    public String updateAppInstance(String appId, String instanceId, String appInstanceJson);

    public String updateAppInstance(String appId, String instanceId, String appInstanceJson, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_updateAppInstance(String appId, String instanceId, String appInstanceJson);

    public Ice.AsyncResult begin_updateAppInstance(String appId, String instanceId, String appInstanceJson, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_updateAppInstance(String appId, String instanceId, String appInstanceJson, Ice.Callback __cb);

    public Ice.AsyncResult begin_updateAppInstance(String appId, String instanceId, String appInstanceJson, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_updateAppInstance(String appId, String instanceId, String appInstanceJson, Callback_AppService_updateAppInstance __cb);

    public Ice.AsyncResult begin_updateAppInstance(String appId, String instanceId, String appInstanceJson, java.util.Map<String, String> __ctx, Callback_AppService_updateAppInstance __cb);

    public Ice.AsyncResult begin_updateAppInstance(String appId, 
                                                   String instanceId, 
                                                   String appInstanceJson, 
                                                   IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_updateAppInstance(String appId, 
                                                   String instanceId, 
                                                   String appInstanceJson, 
                                                   IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                   IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_updateAppInstance(String appId, 
                                                   String instanceId, 
                                                   String appInstanceJson, 
                                                   java.util.Map<String, String> __ctx, 
                                                   IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_updateAppInstance(String appId, 
                                                   String instanceId, 
                                                   String appInstanceJson, 
                                                   java.util.Map<String, String> __ctx, 
                                                   IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                   IceInternal.Functional_BoolCallback __sentCb);

    public String end_updateAppInstance(Ice.AsyncResult __result);

    public String syncServerInfo();

    public String syncServerInfo(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_syncServerInfo();

    public Ice.AsyncResult begin_syncServerInfo(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_syncServerInfo(Ice.Callback __cb);

    public Ice.AsyncResult begin_syncServerInfo(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_syncServerInfo(Callback_AppService_syncServerInfo __cb);

    public Ice.AsyncResult begin_syncServerInfo(java.util.Map<String, String> __ctx, Callback_AppService_syncServerInfo __cb);

    public Ice.AsyncResult begin_syncServerInfo(IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_syncServerInfo(IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_syncServerInfo(java.util.Map<String, String> __ctx, 
                                                IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_syncServerInfo(java.util.Map<String, String> __ctx, 
                                                IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                IceInternal.Functional_BoolCallback __sentCb);

    public String end_syncServerInfo(Ice.AsyncResult __result);

    public String getServerInfo();

    public String getServerInfo(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getServerInfo();

    public Ice.AsyncResult begin_getServerInfo(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getServerInfo(Ice.Callback __cb);

    public Ice.AsyncResult begin_getServerInfo(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getServerInfo(Callback_AppService_getServerInfo __cb);

    public Ice.AsyncResult begin_getServerInfo(java.util.Map<String, String> __ctx, Callback_AppService_getServerInfo __cb);

    public Ice.AsyncResult begin_getServerInfo(IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getServerInfo(IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                               IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_getServerInfo(java.util.Map<String, String> __ctx, 
                                               IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_getServerInfo(java.util.Map<String, String> __ctx, 
                                               IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                               IceInternal.Functional_BoolCallback __sentCb);

    public String end_getServerInfo(Ice.AsyncResult __result);

    public String appSyncStatus(String jsonInfo, String ip, int port);

    public String appSyncStatus(String jsonInfo, String ip, int port, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_appSyncStatus(String jsonInfo, String ip, int port);

    public Ice.AsyncResult begin_appSyncStatus(String jsonInfo, String ip, int port, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_appSyncStatus(String jsonInfo, String ip, int port, Ice.Callback __cb);

    public Ice.AsyncResult begin_appSyncStatus(String jsonInfo, String ip, int port, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_appSyncStatus(String jsonInfo, String ip, int port, Callback_AppService_appSyncStatus __cb);

    public Ice.AsyncResult begin_appSyncStatus(String jsonInfo, String ip, int port, java.util.Map<String, String> __ctx, Callback_AppService_appSyncStatus __cb);

    public Ice.AsyncResult begin_appSyncStatus(String jsonInfo, 
                                               String ip, 
                                               int port, 
                                               IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_appSyncStatus(String jsonInfo, 
                                               String ip, 
                                               int port, 
                                               IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                               IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_appSyncStatus(String jsonInfo, 
                                               String ip, 
                                               int port, 
                                               java.util.Map<String, String> __ctx, 
                                               IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_appSyncStatus(String jsonInfo, 
                                               String ip, 
                                               int port, 
                                               java.util.Map<String, String> __ctx, 
                                               IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                               IceInternal.Functional_BoolCallback __sentCb);

    public String end_appSyncStatus(Ice.AsyncResult __result);

    public String appStopNotify(String appId, String ip, int port);

    public String appStopNotify(String appId, String ip, int port, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_appStopNotify(String appId, String ip, int port);

    public Ice.AsyncResult begin_appStopNotify(String appId, String ip, int port, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_appStopNotify(String appId, String ip, int port, Ice.Callback __cb);

    public Ice.AsyncResult begin_appStopNotify(String appId, String ip, int port, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_appStopNotify(String appId, String ip, int port, Callback_AppService_appStopNotify __cb);

    public Ice.AsyncResult begin_appStopNotify(String appId, String ip, int port, java.util.Map<String, String> __ctx, Callback_AppService_appStopNotify __cb);

    public Ice.AsyncResult begin_appStopNotify(String appId, 
                                               String ip, 
                                               int port, 
                                               IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_appStopNotify(String appId, 
                                               String ip, 
                                               int port, 
                                               IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                               IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_appStopNotify(String appId, 
                                               String ip, 
                                               int port, 
                                               java.util.Map<String, String> __ctx, 
                                               IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_appStopNotify(String appId, 
                                               String ip, 
                                               int port, 
                                               java.util.Map<String, String> __ctx, 
                                               IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                               IceInternal.Functional_BoolCallback __sentCb);

    public String end_appStopNotify(Ice.AsyncResult __result);

    public String appStartupNotify(String appId, String ip, int port);

    public String appStartupNotify(String appId, String ip, int port, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_appStartupNotify(String appId, String ip, int port);

    public Ice.AsyncResult begin_appStartupNotify(String appId, String ip, int port, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_appStartupNotify(String appId, String ip, int port, Ice.Callback __cb);

    public Ice.AsyncResult begin_appStartupNotify(String appId, String ip, int port, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_appStartupNotify(String appId, String ip, int port, Callback_AppService_appStartupNotify __cb);

    public Ice.AsyncResult begin_appStartupNotify(String appId, String ip, int port, java.util.Map<String, String> __ctx, Callback_AppService_appStartupNotify __cb);

    public Ice.AsyncResult begin_appStartupNotify(String appId, 
                                                  String ip, 
                                                  int port, 
                                                  IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_appStartupNotify(String appId, 
                                                  String ip, 
                                                  int port, 
                                                  IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                  IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_appStartupNotify(String appId, 
                                                  String ip, 
                                                  int port, 
                                                  java.util.Map<String, String> __ctx, 
                                                  IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_appStartupNotify(String appId, 
                                                  String ip, 
                                                  int port, 
                                                  java.util.Map<String, String> __ctx, 
                                                  IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                  IceInternal.Functional_BoolCallback __sentCb);

    public String end_appStartupNotify(Ice.AsyncResult __result);

    public void forceAppInstanceShutdown(int seconds);

    public void forceAppInstanceShutdown(int seconds, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_forceAppInstanceShutdown(int seconds);

    public Ice.AsyncResult begin_forceAppInstanceShutdown(int seconds, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_forceAppInstanceShutdown(int seconds, Ice.Callback __cb);

    public Ice.AsyncResult begin_forceAppInstanceShutdown(int seconds, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_forceAppInstanceShutdown(int seconds, Callback_AppService_forceAppInstanceShutdown __cb);

    public Ice.AsyncResult begin_forceAppInstanceShutdown(int seconds, java.util.Map<String, String> __ctx, Callback_AppService_forceAppInstanceShutdown __cb);

    public Ice.AsyncResult begin_forceAppInstanceShutdown(int seconds, 
                                                          IceInternal.Functional_VoidCallback __responseCb, 
                                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_forceAppInstanceShutdown(int seconds, 
                                                          IceInternal.Functional_VoidCallback __responseCb, 
                                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                          IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_forceAppInstanceShutdown(int seconds, 
                                                          java.util.Map<String, String> __ctx, 
                                                          IceInternal.Functional_VoidCallback __responseCb, 
                                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_forceAppInstanceShutdown(int seconds, 
                                                          java.util.Map<String, String> __ctx, 
                                                          IceInternal.Functional_VoidCallback __responseCb, 
                                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                          IceInternal.Functional_BoolCallback __sentCb);

    public void end_forceAppInstanceShutdown(Ice.AsyncResult __result);

    public void forceAppInstanceRestart(int seconds);

    public void forceAppInstanceRestart(int seconds, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_forceAppInstanceRestart(int seconds);

    public Ice.AsyncResult begin_forceAppInstanceRestart(int seconds, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_forceAppInstanceRestart(int seconds, Ice.Callback __cb);

    public Ice.AsyncResult begin_forceAppInstanceRestart(int seconds, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_forceAppInstanceRestart(int seconds, Callback_AppService_forceAppInstanceRestart __cb);

    public Ice.AsyncResult begin_forceAppInstanceRestart(int seconds, java.util.Map<String, String> __ctx, Callback_AppService_forceAppInstanceRestart __cb);

    public Ice.AsyncResult begin_forceAppInstanceRestart(int seconds, 
                                                         IceInternal.Functional_VoidCallback __responseCb, 
                                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_forceAppInstanceRestart(int seconds, 
                                                         IceInternal.Functional_VoidCallback __responseCb, 
                                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                         IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_forceAppInstanceRestart(int seconds, 
                                                         java.util.Map<String, String> __ctx, 
                                                         IceInternal.Functional_VoidCallback __responseCb, 
                                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_forceAppInstanceRestart(int seconds, 
                                                         java.util.Map<String, String> __ctx, 
                                                         IceInternal.Functional_VoidCallback __responseCb, 
                                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                         IceInternal.Functional_BoolCallback __sentCb);

    public void end_forceAppInstanceRestart(Ice.AsyncResult __result);
}
