// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `AppService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.maomao.server.manager.idl;

/**
 * App服务
 **/
public interface AppServicePrx extends Ice.ObjectPrx
{
    public void stopServer();

    public void stopServer(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_stopServer();

    public Ice.AsyncResult begin_stopServer(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_stopServer(Ice.Callback __cb);

    public Ice.AsyncResult begin_stopServer(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_stopServer(Callback_AppService_stopServer __cb);

    public Ice.AsyncResult begin_stopServer(java.util.Map<String, String> __ctx, Callback_AppService_stopServer __cb);

    public Ice.AsyncResult begin_stopServer(IceInternal.Functional_VoidCallback __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_stopServer(IceInternal.Functional_VoidCallback __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                            IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_stopServer(java.util.Map<String, String> __ctx, 
                                            IceInternal.Functional_VoidCallback __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_stopServer(java.util.Map<String, String> __ctx, 
                                            IceInternal.Functional_VoidCallback __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                            IceInternal.Functional_BoolCallback __sentCb);

    public void end_stopServer(Ice.AsyncResult __result);

    /**
     * 返回全部App
     **/
    public java.util.List<App> loadApps();

    /**
     * 返回全部App
     * @param __ctx The Context map to send with the invocation.
     **/
    public java.util.List<App> loadApps(java.util.Map<String, String> __ctx);

    /**
     * 返回全部App
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_loadApps();

    /**
     * 返回全部App
     * @param __ctx The Context map to send with the invocation.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_loadApps(java.util.Map<String, String> __ctx);

    /**
     * 返回全部App
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_loadApps(Ice.Callback __cb);

    /**
     * 返回全部App
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_loadApps(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    /**
     * 返回全部App
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_loadApps(Callback_AppService_loadApps __cb);

    /**
     * 返回全部App
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_loadApps(java.util.Map<String, String> __ctx, Callback_AppService_loadApps __cb);

    /**
     * 返回全部App
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_loadApps(IceInternal.Functional_GenericCallback1<java.util.List<App>> __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    /**
     * 返回全部App
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @param __sentCb The lambda sent callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_loadApps(IceInternal.Functional_GenericCallback1<java.util.List<App>> __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                          IceInternal.Functional_BoolCallback __sentCb);

    /**
     * 返回全部App
     * @param __ctx The Context map to send with the invocation.
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_loadApps(java.util.Map<String, String> __ctx, 
                                          IceInternal.Functional_GenericCallback1<java.util.List<App>> __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    /**
     * 返回全部App
     * @param __ctx The Context map to send with the invocation.
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @param __sentCb The lambda sent callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_loadApps(java.util.Map<String, String> __ctx, 
                                          IceInternal.Functional_GenericCallback1<java.util.List<App>> __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                          IceInternal.Functional_BoolCallback __sentCb);

    /**
     * 返回全部App
     * @param __result The asynchronous result object.
     **/
    public java.util.List<App> end_loadApps(Ice.AsyncResult __result);

    /**
     * 停止一个App的某一个实例
     * instanceId 传递为空时，表示停止该App的全部实例
     **/
    public String stopAppInstance(String appId, String instanceId);

    /**
     * 停止一个App的某一个实例
     * instanceId 传递为空时，表示停止该App的全部实例
     * @param __ctx The Context map to send with the invocation.
     **/
    public String stopAppInstance(String appId, String instanceId, java.util.Map<String, String> __ctx);

    /**
     * 停止一个App的某一个实例
     * instanceId 传递为空时，表示停止该App的全部实例
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_stopAppInstance(String appId, String instanceId);

    /**
     * 停止一个App的某一个实例
     * instanceId 传递为空时，表示停止该App的全部实例
     * @param __ctx The Context map to send with the invocation.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_stopAppInstance(String appId, String instanceId, java.util.Map<String, String> __ctx);

    /**
     * 停止一个App的某一个实例
     * instanceId 传递为空时，表示停止该App的全部实例
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_stopAppInstance(String appId, String instanceId, Ice.Callback __cb);

    /**
     * 停止一个App的某一个实例
     * instanceId 传递为空时，表示停止该App的全部实例
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_stopAppInstance(String appId, String instanceId, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    /**
     * 停止一个App的某一个实例
     * instanceId 传递为空时，表示停止该App的全部实例
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_stopAppInstance(String appId, String instanceId, Callback_AppService_stopAppInstance __cb);

    /**
     * 停止一个App的某一个实例
     * instanceId 传递为空时，表示停止该App的全部实例
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_stopAppInstance(String appId, String instanceId, java.util.Map<String, String> __ctx, Callback_AppService_stopAppInstance __cb);

    /**
     * 停止一个App的某一个实例
     * instanceId 传递为空时，表示停止该App的全部实例
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_stopAppInstance(String appId, 
                                                 String instanceId, 
                                                 IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                 IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    /**
     * 停止一个App的某一个实例
     * instanceId 传递为空时，表示停止该App的全部实例
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @param __sentCb The lambda sent callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_stopAppInstance(String appId, 
                                                 String instanceId, 
                                                 IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                 IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                 IceInternal.Functional_BoolCallback __sentCb);

    /**
     * 停止一个App的某一个实例
     * instanceId 传递为空时，表示停止该App的全部实例
     * @param __ctx The Context map to send with the invocation.
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_stopAppInstance(String appId, 
                                                 String instanceId, 
                                                 java.util.Map<String, String> __ctx, 
                                                 IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                 IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    /**
     * 停止一个App的某一个实例
     * instanceId 传递为空时，表示停止该App的全部实例
     * @param __ctx The Context map to send with the invocation.
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @param __sentCb The lambda sent callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_stopAppInstance(String appId, 
                                                 String instanceId, 
                                                 java.util.Map<String, String> __ctx, 
                                                 IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                 IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                 IceInternal.Functional_BoolCallback __sentCb);

    /**
     * 停止一个App的某一个实例
     * instanceId 传递为空时，表示停止该App的全部实例
     * @param __result The asynchronous result object.
     **/
    public String end_stopAppInstance(Ice.AsyncResult __result);

    /**
     * 停止一个App的某一个实例
     * instanceId 传递为空时，表示停止该App的全部实例
     **/
    public String restartAppInstance(String appId, String instanceId);

    /**
     * 停止一个App的某一个实例
     * instanceId 传递为空时，表示停止该App的全部实例
     * @param __ctx The Context map to send with the invocation.
     **/
    public String restartAppInstance(String appId, String instanceId, java.util.Map<String, String> __ctx);

    /**
     * 停止一个App的某一个实例
     * instanceId 传递为空时，表示停止该App的全部实例
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_restartAppInstance(String appId, String instanceId);

    /**
     * 停止一个App的某一个实例
     * instanceId 传递为空时，表示停止该App的全部实例
     * @param __ctx The Context map to send with the invocation.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_restartAppInstance(String appId, String instanceId, java.util.Map<String, String> __ctx);

    /**
     * 停止一个App的某一个实例
     * instanceId 传递为空时，表示停止该App的全部实例
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_restartAppInstance(String appId, String instanceId, Ice.Callback __cb);

    /**
     * 停止一个App的某一个实例
     * instanceId 传递为空时，表示停止该App的全部实例
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_restartAppInstance(String appId, String instanceId, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    /**
     * 停止一个App的某一个实例
     * instanceId 传递为空时，表示停止该App的全部实例
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_restartAppInstance(String appId, String instanceId, Callback_AppService_restartAppInstance __cb);

    /**
     * 停止一个App的某一个实例
     * instanceId 传递为空时，表示停止该App的全部实例
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_restartAppInstance(String appId, String instanceId, java.util.Map<String, String> __ctx, Callback_AppService_restartAppInstance __cb);

    /**
     * 停止一个App的某一个实例
     * instanceId 传递为空时，表示停止该App的全部实例
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_restartAppInstance(String appId, 
                                                    String instanceId, 
                                                    IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                    IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    /**
     * 停止一个App的某一个实例
     * instanceId 传递为空时，表示停止该App的全部实例
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @param __sentCb The lambda sent callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_restartAppInstance(String appId, 
                                                    String instanceId, 
                                                    IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                    IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                    IceInternal.Functional_BoolCallback __sentCb);

    /**
     * 停止一个App的某一个实例
     * instanceId 传递为空时，表示停止该App的全部实例
     * @param __ctx The Context map to send with the invocation.
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_restartAppInstance(String appId, 
                                                    String instanceId, 
                                                    java.util.Map<String, String> __ctx, 
                                                    IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                    IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    /**
     * 停止一个App的某一个实例
     * instanceId 传递为空时，表示停止该App的全部实例
     * @param __ctx The Context map to send with the invocation.
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @param __sentCb The lambda sent callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_restartAppInstance(String appId, 
                                                    String instanceId, 
                                                    java.util.Map<String, String> __ctx, 
                                                    IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                    IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                    IceInternal.Functional_BoolCallback __sentCb);

    /**
     * 停止一个App的某一个实例
     * instanceId 传递为空时，表示停止该App的全部实例
     * @param __result The asynchronous result object.
     **/
    public String end_restartAppInstance(Ice.AsyncResult __result);

    /**
     * 启动一个App实例
     * instanceId为空时,表示启动该App的全部实例
     **/
    public String startAppInstance(String appId, String instanceId);

    /**
     * 启动一个App实例
     * instanceId为空时,表示启动该App的全部实例
     * @param __ctx The Context map to send with the invocation.
     **/
    public String startAppInstance(String appId, String instanceId, java.util.Map<String, String> __ctx);

    /**
     * 启动一个App实例
     * instanceId为空时,表示启动该App的全部实例
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_startAppInstance(String appId, String instanceId);

    /**
     * 启动一个App实例
     * instanceId为空时,表示启动该App的全部实例
     * @param __ctx The Context map to send with the invocation.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_startAppInstance(String appId, String instanceId, java.util.Map<String, String> __ctx);

    /**
     * 启动一个App实例
     * instanceId为空时,表示启动该App的全部实例
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_startAppInstance(String appId, String instanceId, Ice.Callback __cb);

    /**
     * 启动一个App实例
     * instanceId为空时,表示启动该App的全部实例
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_startAppInstance(String appId, String instanceId, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    /**
     * 启动一个App实例
     * instanceId为空时,表示启动该App的全部实例
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_startAppInstance(String appId, String instanceId, Callback_AppService_startAppInstance __cb);

    /**
     * 启动一个App实例
     * instanceId为空时,表示启动该App的全部实例
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_startAppInstance(String appId, String instanceId, java.util.Map<String, String> __ctx, Callback_AppService_startAppInstance __cb);

    /**
     * 启动一个App实例
     * instanceId为空时,表示启动该App的全部实例
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_startAppInstance(String appId, 
                                                  String instanceId, 
                                                  IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    /**
     * 启动一个App实例
     * instanceId为空时,表示启动该App的全部实例
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @param __sentCb The lambda sent callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_startAppInstance(String appId, 
                                                  String instanceId, 
                                                  IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                  IceInternal.Functional_BoolCallback __sentCb);

    /**
     * 启动一个App实例
     * instanceId为空时,表示启动该App的全部实例
     * @param __ctx The Context map to send with the invocation.
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_startAppInstance(String appId, 
                                                  String instanceId, 
                                                  java.util.Map<String, String> __ctx, 
                                                  IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    /**
     * 启动一个App实例
     * instanceId为空时,表示启动该App的全部实例
     * @param __ctx The Context map to send with the invocation.
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @param __sentCb The lambda sent callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_startAppInstance(String appId, 
                                                  String instanceId, 
                                                  java.util.Map<String, String> __ctx, 
                                                  IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                  IceInternal.Functional_BoolCallback __sentCb);

    /**
     * 启动一个App实例
     * instanceId为空时,表示启动该App的全部实例
     * @param __result The asynchronous result object.
     **/
    public String end_startAppInstance(Ice.AsyncResult __result);

    /**
     * 删除一个App实例
     **/
    public String removeAppInstance(String appId, String instanceId);

    /**
     * 删除一个App实例
     * @param __ctx The Context map to send with the invocation.
     **/
    public String removeAppInstance(String appId, String instanceId, java.util.Map<String, String> __ctx);

    /**
     * 删除一个App实例
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_removeAppInstance(String appId, String instanceId);

    /**
     * 删除一个App实例
     * @param __ctx The Context map to send with the invocation.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_removeAppInstance(String appId, String instanceId, java.util.Map<String, String> __ctx);

    /**
     * 删除一个App实例
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_removeAppInstance(String appId, String instanceId, Ice.Callback __cb);

    /**
     * 删除一个App实例
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_removeAppInstance(String appId, String instanceId, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    /**
     * 删除一个App实例
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_removeAppInstance(String appId, String instanceId, Callback_AppService_removeAppInstance __cb);

    /**
     * 删除一个App实例
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_removeAppInstance(String appId, String instanceId, java.util.Map<String, String> __ctx, Callback_AppService_removeAppInstance __cb);

    /**
     * 删除一个App实例
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_removeAppInstance(String appId, 
                                                   String instanceId, 
                                                   IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    /**
     * 删除一个App实例
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @param __sentCb The lambda sent callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_removeAppInstance(String appId, 
                                                   String instanceId, 
                                                   IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                   IceInternal.Functional_BoolCallback __sentCb);

    /**
     * 删除一个App实例
     * @param __ctx The Context map to send with the invocation.
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_removeAppInstance(String appId, 
                                                   String instanceId, 
                                                   java.util.Map<String, String> __ctx, 
                                                   IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    /**
     * 删除一个App实例
     * @param __ctx The Context map to send with the invocation.
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @param __sentCb The lambda sent callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_removeAppInstance(String appId, 
                                                   String instanceId, 
                                                   java.util.Map<String, String> __ctx, 
                                                   IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                   IceInternal.Functional_BoolCallback __sentCb);

    /**
     * 删除一个App实例
     * @param __result The asynchronous result object.
     **/
    public String end_removeAppInstance(Ice.AsyncResult __result);

    /**
     * Create a new app
     **/
    public String createApp(String appId);

    /**
     * Create a new app
     * @param __ctx The Context map to send with the invocation.
     **/
    public String createApp(String appId, java.util.Map<String, String> __ctx);

    /**
     * Create a new app
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_createApp(String appId);

    /**
     * Create a new app
     * @param __ctx The Context map to send with the invocation.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_createApp(String appId, java.util.Map<String, String> __ctx);

    /**
     * Create a new app
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_createApp(String appId, Ice.Callback __cb);

    /**
     * Create a new app
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_createApp(String appId, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    /**
     * Create a new app
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_createApp(String appId, Callback_AppService_createApp __cb);

    /**
     * Create a new app
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_createApp(String appId, java.util.Map<String, String> __ctx, Callback_AppService_createApp __cb);

    /**
     * Create a new app
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_createApp(String appId, 
                                           IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    /**
     * Create a new app
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @param __sentCb The lambda sent callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_createApp(String appId, 
                                           IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                           IceInternal.Functional_BoolCallback __sentCb);

    /**
     * Create a new app
     * @param __ctx The Context map to send with the invocation.
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_createApp(String appId, 
                                           java.util.Map<String, String> __ctx, 
                                           IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    /**
     * Create a new app
     * @param __ctx The Context map to send with the invocation.
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @param __sentCb The lambda sent callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_createApp(String appId, 
                                           java.util.Map<String, String> __ctx, 
                                           IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                           IceInternal.Functional_BoolCallback __sentCb);

    /**
     * Create a new app
     * @param __result The asynchronous result object.
     **/
    public String end_createApp(Ice.AsyncResult __result);

    /**
     * 删除一个App
     **/
    public String removeApp(String appId);

    /**
     * 删除一个App
     * @param __ctx The Context map to send with the invocation.
     **/
    public String removeApp(String appId, java.util.Map<String, String> __ctx);

    /**
     * 删除一个App
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_removeApp(String appId);

    /**
     * 删除一个App
     * @param __ctx The Context map to send with the invocation.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_removeApp(String appId, java.util.Map<String, String> __ctx);

    /**
     * 删除一个App
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_removeApp(String appId, Ice.Callback __cb);

    /**
     * 删除一个App
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_removeApp(String appId, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    /**
     * 删除一个App
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_removeApp(String appId, Callback_AppService_removeApp __cb);

    /**
     * 删除一个App
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_removeApp(String appId, java.util.Map<String, String> __ctx, Callback_AppService_removeApp __cb);

    /**
     * 删除一个App
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_removeApp(String appId, 
                                           IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    /**
     * 删除一个App
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @param __sentCb The lambda sent callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_removeApp(String appId, 
                                           IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                           IceInternal.Functional_BoolCallback __sentCb);

    /**
     * 删除一个App
     * @param __ctx The Context map to send with the invocation.
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_removeApp(String appId, 
                                           java.util.Map<String, String> __ctx, 
                                           IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    /**
     * 删除一个App
     * @param __ctx The Context map to send with the invocation.
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @param __sentCb The lambda sent callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_removeApp(String appId, 
                                           java.util.Map<String, String> __ctx, 
                                           IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                           IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                           IceInternal.Functional_BoolCallback __sentCb);

    /**
     * 删除一个App
     * @param __result The asynchronous result object.
     **/
    public String end_removeApp(Ice.AsyncResult __result);

    /**
     * 停止一个App及其所有实例
     **/
    public String stopApp(String appId);

    /**
     * 停止一个App及其所有实例
     * @param __ctx The Context map to send with the invocation.
     **/
    public String stopApp(String appId, java.util.Map<String, String> __ctx);

    /**
     * 停止一个App及其所有实例
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_stopApp(String appId);

    /**
     * 停止一个App及其所有实例
     * @param __ctx The Context map to send with the invocation.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_stopApp(String appId, java.util.Map<String, String> __ctx);

    /**
     * 停止一个App及其所有实例
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_stopApp(String appId, Ice.Callback __cb);

    /**
     * 停止一个App及其所有实例
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_stopApp(String appId, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    /**
     * 停止一个App及其所有实例
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_stopApp(String appId, Callback_AppService_stopApp __cb);

    /**
     * 停止一个App及其所有实例
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_stopApp(String appId, java.util.Map<String, String> __ctx, Callback_AppService_stopApp __cb);

    /**
     * 停止一个App及其所有实例
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_stopApp(String appId, 
                                         IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    /**
     * 停止一个App及其所有实例
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @param __sentCb The lambda sent callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_stopApp(String appId, 
                                         IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb);

    /**
     * 停止一个App及其所有实例
     * @param __ctx The Context map to send with the invocation.
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_stopApp(String appId, 
                                         java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    /**
     * 停止一个App及其所有实例
     * @param __ctx The Context map to send with the invocation.
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @param __sentCb The lambda sent callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_stopApp(String appId, 
                                         java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb);

    /**
     * 停止一个App及其所有实例
     * @param __result The asynchronous result object.
     **/
    public String end_stopApp(Ice.AsyncResult __result);

    /**
     * 启动App的所有实例
     **/
    public String startApp(String appId);

    /**
     * 启动App的所有实例
     * @param __ctx The Context map to send with the invocation.
     **/
    public String startApp(String appId, java.util.Map<String, String> __ctx);

    /**
     * 启动App的所有实例
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_startApp(String appId);

    /**
     * 启动App的所有实例
     * @param __ctx The Context map to send with the invocation.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_startApp(String appId, java.util.Map<String, String> __ctx);

    /**
     * 启动App的所有实例
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_startApp(String appId, Ice.Callback __cb);

    /**
     * 启动App的所有实例
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_startApp(String appId, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    /**
     * 启动App的所有实例
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_startApp(String appId, Callback_AppService_startApp __cb);

    /**
     * 启动App的所有实例
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_startApp(String appId, java.util.Map<String, String> __ctx, Callback_AppService_startApp __cb);

    /**
     * 启动App的所有实例
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_startApp(String appId, 
                                          IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    /**
     * 启动App的所有实例
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @param __sentCb The lambda sent callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_startApp(String appId, 
                                          IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                          IceInternal.Functional_BoolCallback __sentCb);

    /**
     * 启动App的所有实例
     * @param __ctx The Context map to send with the invocation.
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_startApp(String appId, 
                                          java.util.Map<String, String> __ctx, 
                                          IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    /**
     * 启动App的所有实例
     * @param __ctx The Context map to send with the invocation.
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @param __sentCb The lambda sent callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_startApp(String appId, 
                                          java.util.Map<String, String> __ctx, 
                                          IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                          IceInternal.Functional_BoolCallback __sentCb);

    /**
     * 启动App的所有实例
     * @param __result The asynchronous result object.
     **/
    public String end_startApp(Ice.AsyncResult __result);

    /**
     * 重启一个应用的所有实例
     **/
    public String restartApp(String appId);

    /**
     * 重启一个应用的所有实例
     * @param __ctx The Context map to send with the invocation.
     **/
    public String restartApp(String appId, java.util.Map<String, String> __ctx);

    /**
     * 重启一个应用的所有实例
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_restartApp(String appId);

    /**
     * 重启一个应用的所有实例
     * @param __ctx The Context map to send with the invocation.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_restartApp(String appId, java.util.Map<String, String> __ctx);

    /**
     * 重启一个应用的所有实例
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_restartApp(String appId, Ice.Callback __cb);

    /**
     * 重启一个应用的所有实例
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_restartApp(String appId, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    /**
     * 重启一个应用的所有实例
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_restartApp(String appId, Callback_AppService_restartApp __cb);

    /**
     * 重启一个应用的所有实例
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_restartApp(String appId, java.util.Map<String, String> __ctx, Callback_AppService_restartApp __cb);

    /**
     * 重启一个应用的所有实例
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_restartApp(String appId, 
                                            IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    /**
     * 重启一个应用的所有实例
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @param __sentCb The lambda sent callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_restartApp(String appId, 
                                            IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                            IceInternal.Functional_BoolCallback __sentCb);

    /**
     * 重启一个应用的所有实例
     * @param __ctx The Context map to send with the invocation.
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_restartApp(String appId, 
                                            java.util.Map<String, String> __ctx, 
                                            IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    /**
     * 重启一个应用的所有实例
     * @param __ctx The Context map to send with the invocation.
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @param __sentCb The lambda sent callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_restartApp(String appId, 
                                            java.util.Map<String, String> __ctx, 
                                            IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                            IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                            IceInternal.Functional_BoolCallback __sentCb);

    /**
     * 重启一个应用的所有实例
     * @param __result The asynchronous result object.
     **/
    public String end_restartApp(Ice.AsyncResult __result);

    /**
     * 创建一个新的App实例
     **/
    public String createAppInstance(String appId, String appInstanceJson);

    /**
     * 创建一个新的App实例
     * @param __ctx The Context map to send with the invocation.
     **/
    public String createAppInstance(String appId, String appInstanceJson, java.util.Map<String, String> __ctx);

    /**
     * 创建一个新的App实例
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_createAppInstance(String appId, String appInstanceJson);

    /**
     * 创建一个新的App实例
     * @param __ctx The Context map to send with the invocation.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_createAppInstance(String appId, String appInstanceJson, java.util.Map<String, String> __ctx);

    /**
     * 创建一个新的App实例
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_createAppInstance(String appId, String appInstanceJson, Ice.Callback __cb);

    /**
     * 创建一个新的App实例
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_createAppInstance(String appId, String appInstanceJson, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    /**
     * 创建一个新的App实例
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_createAppInstance(String appId, String appInstanceJson, Callback_AppService_createAppInstance __cb);

    /**
     * 创建一个新的App实例
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_createAppInstance(String appId, String appInstanceJson, java.util.Map<String, String> __ctx, Callback_AppService_createAppInstance __cb);

    /**
     * 创建一个新的App实例
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_createAppInstance(String appId, 
                                                   String appInstanceJson, 
                                                   IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    /**
     * 创建一个新的App实例
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @param __sentCb The lambda sent callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_createAppInstance(String appId, 
                                                   String appInstanceJson, 
                                                   IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                   IceInternal.Functional_BoolCallback __sentCb);

    /**
     * 创建一个新的App实例
     * @param __ctx The Context map to send with the invocation.
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_createAppInstance(String appId, 
                                                   String appInstanceJson, 
                                                   java.util.Map<String, String> __ctx, 
                                                   IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    /**
     * 创建一个新的App实例
     * @param __ctx The Context map to send with the invocation.
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @param __sentCb The lambda sent callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_createAppInstance(String appId, 
                                                   String appInstanceJson, 
                                                   java.util.Map<String, String> __ctx, 
                                                   IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                   IceInternal.Functional_BoolCallback __sentCb);

    /**
     * 创建一个新的App实例
     * @param __result The asynchronous result object.
     **/
    public String end_createAppInstance(Ice.AsyncResult __result);

    /**
     * 更新一个现有的App实例
     **/
    public String updateAppInstance(String appId, String instanceId, String appInstanceJson);

    /**
     * 更新一个现有的App实例
     * @param __ctx The Context map to send with the invocation.
     **/
    public String updateAppInstance(String appId, String instanceId, String appInstanceJson, java.util.Map<String, String> __ctx);

    /**
     * 更新一个现有的App实例
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_updateAppInstance(String appId, String instanceId, String appInstanceJson);

    /**
     * 更新一个现有的App实例
     * @param __ctx The Context map to send with the invocation.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_updateAppInstance(String appId, String instanceId, String appInstanceJson, java.util.Map<String, String> __ctx);

    /**
     * 更新一个现有的App实例
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_updateAppInstance(String appId, String instanceId, String appInstanceJson, Ice.Callback __cb);

    /**
     * 更新一个现有的App实例
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_updateAppInstance(String appId, String instanceId, String appInstanceJson, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    /**
     * 更新一个现有的App实例
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_updateAppInstance(String appId, String instanceId, String appInstanceJson, Callback_AppService_updateAppInstance __cb);

    /**
     * 更新一个现有的App实例
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_updateAppInstance(String appId, String instanceId, String appInstanceJson, java.util.Map<String, String> __ctx, Callback_AppService_updateAppInstance __cb);

    /**
     * 更新一个现有的App实例
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_updateAppInstance(String appId, 
                                                   String instanceId, 
                                                   String appInstanceJson, 
                                                   IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    /**
     * 更新一个现有的App实例
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @param __sentCb The lambda sent callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_updateAppInstance(String appId, 
                                                   String instanceId, 
                                                   String appInstanceJson, 
                                                   IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                   IceInternal.Functional_BoolCallback __sentCb);

    /**
     * 更新一个现有的App实例
     * @param __ctx The Context map to send with the invocation.
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_updateAppInstance(String appId, 
                                                   String instanceId, 
                                                   String appInstanceJson, 
                                                   java.util.Map<String, String> __ctx, 
                                                   IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    /**
     * 更新一个现有的App实例
     * @param __ctx The Context map to send with the invocation.
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @param __sentCb The lambda sent callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_updateAppInstance(String appId, 
                                                   String instanceId, 
                                                   String appInstanceJson, 
                                                   java.util.Map<String, String> __ctx, 
                                                   IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                   IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                   IceInternal.Functional_BoolCallback __sentCb);

    /**
     * 更新一个现有的App实例
     * @param __result The asynchronous result object.
     **/
    public String end_updateAppInstance(Ice.AsyncResult __result);

    /**
     * 同步服务器信息
     **/
    public String syncServerInfo();

    /**
     * 同步服务器信息
     * @param __ctx The Context map to send with the invocation.
     **/
    public String syncServerInfo(java.util.Map<String, String> __ctx);

    /**
     * 同步服务器信息
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_syncServerInfo();

    /**
     * 同步服务器信息
     * @param __ctx The Context map to send with the invocation.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_syncServerInfo(java.util.Map<String, String> __ctx);

    /**
     * 同步服务器信息
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_syncServerInfo(Ice.Callback __cb);

    /**
     * 同步服务器信息
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_syncServerInfo(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    /**
     * 同步服务器信息
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_syncServerInfo(Callback_AppService_syncServerInfo __cb);

    /**
     * 同步服务器信息
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_syncServerInfo(java.util.Map<String, String> __ctx, Callback_AppService_syncServerInfo __cb);

    /**
     * 同步服务器信息
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_syncServerInfo(IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    /**
     * 同步服务器信息
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @param __sentCb The lambda sent callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_syncServerInfo(IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                IceInternal.Functional_BoolCallback __sentCb);

    /**
     * 同步服务器信息
     * @param __ctx The Context map to send with the invocation.
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_syncServerInfo(java.util.Map<String, String> __ctx, 
                                                IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    /**
     * 同步服务器信息
     * @param __ctx The Context map to send with the invocation.
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @param __sentCb The lambda sent callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_syncServerInfo(java.util.Map<String, String> __ctx, 
                                                IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                IceInternal.Functional_BoolCallback __sentCb);

    /**
     * 同步服务器信息
     * @param __result The asynchronous result object.
     **/
    public String end_syncServerInfo(Ice.AsyncResult __result);

    /**
     * 　返回服务器信息
     **/
    public String getHdpServerInfo();

    /**
     * 　返回服务器信息
     * @param __ctx The Context map to send with the invocation.
     **/
    public String getHdpServerInfo(java.util.Map<String, String> __ctx);

    /**
     * 　返回服务器信息
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_getHdpServerInfo();

    /**
     * 　返回服务器信息
     * @param __ctx The Context map to send with the invocation.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_getHdpServerInfo(java.util.Map<String, String> __ctx);

    /**
     * 　返回服务器信息
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_getHdpServerInfo(Ice.Callback __cb);

    /**
     * 　返回服务器信息
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_getHdpServerInfo(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    /**
     * 　返回服务器信息
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_getHdpServerInfo(Callback_AppService_getHdpServerInfo __cb);

    /**
     * 　返回服务器信息
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_getHdpServerInfo(java.util.Map<String, String> __ctx, Callback_AppService_getHdpServerInfo __cb);

    /**
     * 　返回服务器信息
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_getHdpServerInfo(IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    /**
     * 　返回服务器信息
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @param __sentCb The lambda sent callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_getHdpServerInfo(IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                  IceInternal.Functional_BoolCallback __sentCb);

    /**
     * 　返回服务器信息
     * @param __ctx The Context map to send with the invocation.
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_getHdpServerInfo(java.util.Map<String, String> __ctx, 
                                                  IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    /**
     * 　返回服务器信息
     * @param __ctx The Context map to send with the invocation.
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @param __sentCb The lambda sent callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_getHdpServerInfo(java.util.Map<String, String> __ctx, 
                                                  IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                  IceInternal.Functional_BoolCallback __sentCb);

    /**
     * 　返回服务器信息
     * @param __result The asynchronous result object.
     **/
    public String end_getHdpServerInfo(Ice.AsyncResult __result);

    /**
     * 　app与hdpserver保持同步状态
     **/
    public String appSyncStatus(String jsonInfo, String ip, int port);

    /**
     * 　app与hdpserver保持同步状态
     * @param __ctx The Context map to send with the invocation.
     **/
    public String appSyncStatus(String jsonInfo, String ip, int port, java.util.Map<String, String> __ctx);

    /**
     * 　app与hdpserver保持同步状态
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_appSyncStatus(String jsonInfo, String ip, int port);

    /**
     * 　app与hdpserver保持同步状态
     * @param __ctx The Context map to send with the invocation.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_appSyncStatus(String jsonInfo, String ip, int port, java.util.Map<String, String> __ctx);

    /**
     * 　app与hdpserver保持同步状态
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_appSyncStatus(String jsonInfo, String ip, int port, Ice.Callback __cb);

    /**
     * 　app与hdpserver保持同步状态
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_appSyncStatus(String jsonInfo, String ip, int port, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    /**
     * 　app与hdpserver保持同步状态
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_appSyncStatus(String jsonInfo, String ip, int port, Callback_AppService_appSyncStatus __cb);

    /**
     * 　app与hdpserver保持同步状态
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_appSyncStatus(String jsonInfo, String ip, int port, java.util.Map<String, String> __ctx, Callback_AppService_appSyncStatus __cb);

    /**
     * 　app与hdpserver保持同步状态
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_appSyncStatus(String jsonInfo, 
                                               String ip, 
                                               int port, 
                                               IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    /**
     * 　app与hdpserver保持同步状态
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @param __sentCb The lambda sent callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_appSyncStatus(String jsonInfo, 
                                               String ip, 
                                               int port, 
                                               IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                               IceInternal.Functional_BoolCallback __sentCb);

    /**
     * 　app与hdpserver保持同步状态
     * @param __ctx The Context map to send with the invocation.
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_appSyncStatus(String jsonInfo, 
                                               String ip, 
                                               int port, 
                                               java.util.Map<String, String> __ctx, 
                                               IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    /**
     * 　app与hdpserver保持同步状态
     * @param __ctx The Context map to send with the invocation.
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @param __sentCb The lambda sent callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_appSyncStatus(String jsonInfo, 
                                               String ip, 
                                               int port, 
                                               java.util.Map<String, String> __ctx, 
                                               IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                               IceInternal.Functional_BoolCallback __sentCb);

    /**
     * 　app与hdpserver保持同步状态
     * @param __result The asynchronous result object.
     **/
    public String end_appSyncStatus(Ice.AsyncResult __result);

    /**
     * app停止时发送给hdp server的通知事件
     **/
    public String appStopNotify(String appId, String ip, int port);

    /**
     * app停止时发送给hdp server的通知事件
     * @param __ctx The Context map to send with the invocation.
     **/
    public String appStopNotify(String appId, String ip, int port, java.util.Map<String, String> __ctx);

    /**
     * app停止时发送给hdp server的通知事件
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_appStopNotify(String appId, String ip, int port);

    /**
     * app停止时发送给hdp server的通知事件
     * @param __ctx The Context map to send with the invocation.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_appStopNotify(String appId, String ip, int port, java.util.Map<String, String> __ctx);

    /**
     * app停止时发送给hdp server的通知事件
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_appStopNotify(String appId, String ip, int port, Ice.Callback __cb);

    /**
     * app停止时发送给hdp server的通知事件
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_appStopNotify(String appId, String ip, int port, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    /**
     * app停止时发送给hdp server的通知事件
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_appStopNotify(String appId, String ip, int port, Callback_AppService_appStopNotify __cb);

    /**
     * app停止时发送给hdp server的通知事件
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_appStopNotify(String appId, String ip, int port, java.util.Map<String, String> __ctx, Callback_AppService_appStopNotify __cb);

    /**
     * app停止时发送给hdp server的通知事件
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_appStopNotify(String appId, 
                                               String ip, 
                                               int port, 
                                               IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    /**
     * app停止时发送给hdp server的通知事件
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @param __sentCb The lambda sent callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_appStopNotify(String appId, 
                                               String ip, 
                                               int port, 
                                               IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                               IceInternal.Functional_BoolCallback __sentCb);

    /**
     * app停止时发送给hdp server的通知事件
     * @param __ctx The Context map to send with the invocation.
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_appStopNotify(String appId, 
                                               String ip, 
                                               int port, 
                                               java.util.Map<String, String> __ctx, 
                                               IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    /**
     * app停止时发送给hdp server的通知事件
     * @param __ctx The Context map to send with the invocation.
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @param __sentCb The lambda sent callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_appStopNotify(String appId, 
                                               String ip, 
                                               int port, 
                                               java.util.Map<String, String> __ctx, 
                                               IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                               IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                               IceInternal.Functional_BoolCallback __sentCb);

    /**
     * app停止时发送给hdp server的通知事件
     * @param __result The asynchronous result object.
     **/
    public String end_appStopNotify(Ice.AsyncResult __result);

    /**
     * app启动完毕后，发送通知
     **/
    public String appStartupNotify(String appId, String ip, int port);

    /**
     * app启动完毕后，发送通知
     * @param __ctx The Context map to send with the invocation.
     **/
    public String appStartupNotify(String appId, String ip, int port, java.util.Map<String, String> __ctx);

    /**
     * app启动完毕后，发送通知
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_appStartupNotify(String appId, String ip, int port);

    /**
     * app启动完毕后，发送通知
     * @param __ctx The Context map to send with the invocation.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_appStartupNotify(String appId, String ip, int port, java.util.Map<String, String> __ctx);

    /**
     * app启动完毕后，发送通知
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_appStartupNotify(String appId, String ip, int port, Ice.Callback __cb);

    /**
     * app启动完毕后，发送通知
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_appStartupNotify(String appId, String ip, int port, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    /**
     * app启动完毕后，发送通知
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_appStartupNotify(String appId, String ip, int port, Callback_AppService_appStartupNotify __cb);

    /**
     * app启动完毕后，发送通知
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_appStartupNotify(String appId, String ip, int port, java.util.Map<String, String> __ctx, Callback_AppService_appStartupNotify __cb);

    /**
     * app启动完毕后，发送通知
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_appStartupNotify(String appId, 
                                                  String ip, 
                                                  int port, 
                                                  IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    /**
     * app启动完毕后，发送通知
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @param __sentCb The lambda sent callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_appStartupNotify(String appId, 
                                                  String ip, 
                                                  int port, 
                                                  IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                  IceInternal.Functional_BoolCallback __sentCb);

    /**
     * app启动完毕后，发送通知
     * @param __ctx The Context map to send with the invocation.
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_appStartupNotify(String appId, 
                                                  String ip, 
                                                  int port, 
                                                  java.util.Map<String, String> __ctx, 
                                                  IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    /**
     * app启动完毕后，发送通知
     * @param __ctx The Context map to send with the invocation.
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @param __sentCb The lambda sent callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_appStartupNotify(String appId, 
                                                  String ip, 
                                                  int port, 
                                                  java.util.Map<String, String> __ctx, 
                                                  IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                  IceInternal.Functional_BoolCallback __sentCb);

    /**
     * app启动完毕后，发送通知
     * @param __result The asynchronous result object.
     **/
    public String end_appStartupNotify(Ice.AsyncResult __result);

    /**
     * 迫使服务器关闭
     **/
    public void forceAppInstanceShutdown(int seconds);

    /**
     * 迫使服务器关闭
     * @param __ctx The Context map to send with the invocation.
     **/
    public void forceAppInstanceShutdown(int seconds, java.util.Map<String, String> __ctx);

    /**
     * 迫使服务器关闭
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_forceAppInstanceShutdown(int seconds);

    /**
     * 迫使服务器关闭
     * @param __ctx The Context map to send with the invocation.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_forceAppInstanceShutdown(int seconds, java.util.Map<String, String> __ctx);

    /**
     * 迫使服务器关闭
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_forceAppInstanceShutdown(int seconds, Ice.Callback __cb);

    /**
     * 迫使服务器关闭
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_forceAppInstanceShutdown(int seconds, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    /**
     * 迫使服务器关闭
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_forceAppInstanceShutdown(int seconds, Callback_AppService_forceAppInstanceShutdown __cb);

    /**
     * 迫使服务器关闭
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_forceAppInstanceShutdown(int seconds, java.util.Map<String, String> __ctx, Callback_AppService_forceAppInstanceShutdown __cb);

    /**
     * 迫使服务器关闭
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_forceAppInstanceShutdown(int seconds, 
                                                          IceInternal.Functional_VoidCallback __responseCb, 
                                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    /**
     * 迫使服务器关闭
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @param __sentCb The lambda sent callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_forceAppInstanceShutdown(int seconds, 
                                                          IceInternal.Functional_VoidCallback __responseCb, 
                                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                          IceInternal.Functional_BoolCallback __sentCb);

    /**
     * 迫使服务器关闭
     * @param __ctx The Context map to send with the invocation.
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_forceAppInstanceShutdown(int seconds, 
                                                          java.util.Map<String, String> __ctx, 
                                                          IceInternal.Functional_VoidCallback __responseCb, 
                                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    /**
     * 迫使服务器关闭
     * @param __ctx The Context map to send with the invocation.
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @param __sentCb The lambda sent callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_forceAppInstanceShutdown(int seconds, 
                                                          java.util.Map<String, String> __ctx, 
                                                          IceInternal.Functional_VoidCallback __responseCb, 
                                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                          IceInternal.Functional_BoolCallback __sentCb);

    /**
     * 迫使服务器关闭
     * @param __result The asynchronous result object.
     **/
    public void end_forceAppInstanceShutdown(Ice.AsyncResult __result);

    /**
     * 迫使服务器关闭
     **/
    public void forceAppInstanceRestart(int seconds);

    /**
     * 迫使服务器关闭
     * @param __ctx The Context map to send with the invocation.
     **/
    public void forceAppInstanceRestart(int seconds, java.util.Map<String, String> __ctx);

    /**
     * 迫使服务器关闭
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_forceAppInstanceRestart(int seconds);

    /**
     * 迫使服务器关闭
     * @param __ctx The Context map to send with the invocation.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_forceAppInstanceRestart(int seconds, java.util.Map<String, String> __ctx);

    /**
     * 迫使服务器关闭
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_forceAppInstanceRestart(int seconds, Ice.Callback __cb);

    /**
     * 迫使服务器关闭
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_forceAppInstanceRestart(int seconds, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    /**
     * 迫使服务器关闭
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_forceAppInstanceRestart(int seconds, Callback_AppService_forceAppInstanceRestart __cb);

    /**
     * 迫使服务器关闭
     * @param __ctx The Context map to send with the invocation.
     * @param __cb The asynchronous callback object.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_forceAppInstanceRestart(int seconds, java.util.Map<String, String> __ctx, Callback_AppService_forceAppInstanceRestart __cb);

    /**
     * 迫使服务器关闭
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_forceAppInstanceRestart(int seconds, 
                                                         IceInternal.Functional_VoidCallback __responseCb, 
                                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    /**
     * 迫使服务器关闭
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @param __sentCb The lambda sent callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_forceAppInstanceRestart(int seconds, 
                                                         IceInternal.Functional_VoidCallback __responseCb, 
                                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                         IceInternal.Functional_BoolCallback __sentCb);

    /**
     * 迫使服务器关闭
     * @param __ctx The Context map to send with the invocation.
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_forceAppInstanceRestart(int seconds, 
                                                         java.util.Map<String, String> __ctx, 
                                                         IceInternal.Functional_VoidCallback __responseCb, 
                                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    /**
     * 迫使服务器关闭
     * @param __ctx The Context map to send with the invocation.
     * @param __responseCb The lambda response callback.
     * @param __exceptionCb The lambda exception callback.
     * @param __sentCb The lambda sent callback.
     * @return The asynchronous result object.
     **/
    public Ice.AsyncResult begin_forceAppInstanceRestart(int seconds, 
                                                         java.util.Map<String, String> __ctx, 
                                                         IceInternal.Functional_VoidCallback __responseCb, 
                                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                         IceInternal.Functional_BoolCallback __sentCb);

    /**
     * 迫使服务器关闭
     * @param __result The asynchronous result object.
     **/
    public void end_forceAppInstanceRestart(Ice.AsyncResult __result);
}
