// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `AppService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.maomao.server.manager.idl;

public interface AppService extends Ice.Object,
                                    _AppServiceOperations, _AppServiceOperationsNC
{
    public static final String ice_staticId = "::idl::AppService";

    public static final long serialVersionUID = -3211585635373916128L;
}
