// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `SSHServerService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.maomao.server.manager.idl;

public final class SSHServerServiceHolder extends Ice.ObjectHolderBase<SSHServerService>
{
    public
    SSHServerServiceHolder()
    {
    }

    public
    SSHServerServiceHolder(SSHServerService value)
    {
        this.value = value;
    }

    public void
    patch(Ice.Object v)
    {
        if(v == null || v instanceof SSHServerService)
        {
            value = (SSHServerService)v;
        }
        else
        {
            IceInternal.Ex.throwUOE(type(), v);
        }
    }

    public String
    type()
    {
        return _SSHServerServiceDisp.ice_staticId();
    }
}
