// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `SSHServerService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.maomao.server.manager.idl;

/**
 * App服务
 **/
public interface SSHServerService extends Ice.Object,
                                          _SSHServerServiceOperations, _SSHServerServiceOperationsNC
{
    public static final String ice_staticId = "::idl::SSHServerService";

    public static final long serialVersionUID = -3132851727397177492L;
}
