// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `App.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    var Ice = require("ice").Ice;
    var __M = Ice.__M;
    var Slice = Ice.Slice;

    var idl = __M.module("idl");

    idl.App = Slice.defineStruct(
        function(pk, appid, name, description, email, developer, versionLabel, version)
        {
            this.pk = pk !== undefined ? pk : "";
            this.appid = appid !== undefined ? appid : "";
            this.name = name !== undefined ? name : "";
            this.description = description !== undefined ? description : "";
            this.email = email !== undefined ? email : "";
            this.developer = developer !== undefined ? developer : "";
            this.versionLabel = versionLabel !== undefined ? versionLabel : "";
            this.version = version !== undefined ? version : 0;
        },
        true,
        function(__os)
        {
            __os.writeString(this.pk);
            __os.writeString(this.appid);
            __os.writeString(this.name);
            __os.writeString(this.description);
            __os.writeString(this.email);
            __os.writeString(this.developer);
            __os.writeString(this.versionLabel);
            __os.writeInt(this.version);
        },
        function(__is)
        {
            this.pk = __is.readString();
            this.appid = __is.readString();
            this.name = __is.readString();
            this.description = __is.readString();
            this.email = __is.readString();
            this.developer = __is.readString();
            this.versionLabel = __is.readString();
            this.version = __is.readInt();
        },
        11, 
        false);
    exports.idl = idl;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : this.Ice.__require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : this));
