// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `ScheduleService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.maomao.server.plugin.schedule.idl;

/**
 * Provides type-specific helper functions.
 **/
public final class ScheduleServicePrxHelper extends Ice.ObjectPrxHelperBase implements ScheduleServicePrx
{
    private static final String __executeSchedule_name = "executeSchedule";

    public String executeSchedule(String serviceName)
    {
        return executeSchedule(serviceName, null, false);
    }

    public String executeSchedule(String serviceName, java.util.Map<String, String> __ctx)
    {
        return executeSchedule(serviceName, __ctx, true);
    }

    private String executeSchedule(String serviceName, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        __checkTwowayOnly(__executeSchedule_name);
        return end_executeSchedule(begin_executeSchedule(serviceName, __ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_executeSchedule(String serviceName)
    {
        return begin_executeSchedule(serviceName, null, false, false, null);
    }

    public Ice.AsyncResult begin_executeSchedule(String serviceName, java.util.Map<String, String> __ctx)
    {
        return begin_executeSchedule(serviceName, __ctx, true, false, null);
    }

    public Ice.AsyncResult begin_executeSchedule(String serviceName, Ice.Callback __cb)
    {
        return begin_executeSchedule(serviceName, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_executeSchedule(String serviceName, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_executeSchedule(serviceName, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_executeSchedule(String serviceName, Callback_ScheduleService_executeSchedule __cb)
    {
        return begin_executeSchedule(serviceName, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_executeSchedule(String serviceName, java.util.Map<String, String> __ctx, Callback_ScheduleService_executeSchedule __cb)
    {
        return begin_executeSchedule(serviceName, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_executeSchedule(String serviceName, 
                                                 IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                 IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_executeSchedule(serviceName, null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_executeSchedule(String serviceName, 
                                                 IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                 IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                 IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_executeSchedule(serviceName, null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_executeSchedule(String serviceName, 
                                                 java.util.Map<String, String> __ctx, 
                                                 IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                 IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_executeSchedule(serviceName, __ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_executeSchedule(String serviceName, 
                                                 java.util.Map<String, String> __ctx, 
                                                 IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                 IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                 IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_executeSchedule(serviceName, __ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_executeSchedule(String serviceName, 
                                                  java.util.Map<String, String> __ctx, 
                                                  boolean __explicitCtx, 
                                                  boolean __synchronous, 
                                                  IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                  IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                  IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_executeSchedule(serviceName, __ctx, __explicitCtx, __synchronous, 
                                     new IceInternal.Functional_TwowayCallbackArg1<String>(__responseCb, __exceptionCb, __sentCb)
                                         {
                                             public final void __completed(Ice.AsyncResult __result)
                                             {
                                                 ScheduleServicePrxHelper.__executeSchedule_completed(this, __result);
                                             }
                                         });
    }

    private Ice.AsyncResult begin_executeSchedule(String serviceName, 
                                                  java.util.Map<String, String> __ctx, 
                                                  boolean __explicitCtx, 
                                                  boolean __synchronous, 
                                                  IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__executeSchedule_name);
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__executeSchedule_name, __cb);
        try
        {
            __result.prepare(__executeSchedule_name, Ice.OperationMode.Normal, __ctx, __explicitCtx, __synchronous);
            IceInternal.BasicStream __os = __result.startWriteParams(Ice.FormatType.DefaultFormat);
            __os.writeString(serviceName);
            __result.endWriteParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public String end_executeSchedule(Ice.AsyncResult __iresult)
    {
        IceInternal.OutgoingAsync __result = IceInternal.OutgoingAsync.check(__iresult, this, __executeSchedule_name);
        try
        {
            if(!__result.__wait())
            {
                try
                {
                    __result.throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.startReadParams();
            String __ret;
            __ret = __is.readString();
            __result.endReadParams();
            return __ret;
        }
        finally
        {
            if(__result != null)
            {
                __result.cacheMessageBuffers();
            }
        }
    }

    static public void __executeSchedule_completed(Ice.TwowayCallbackArg1<String> __cb, Ice.AsyncResult __result)
    {
        com.maomao.server.plugin.schedule.idl.ScheduleServicePrx __proxy = (com.maomao.server.plugin.schedule.idl.ScheduleServicePrx)__result.getProxy();
        String __ret = null;
        try
        {
            __ret = __proxy.end_executeSchedule(__result);
        }
        catch(Ice.LocalException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        catch(Ice.SystemException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        __cb.response(__ret);
    }

    private static final String __registSchedule_name = "registSchedule";

    public String registSchedule(String connectionUrl, String serviceName, String cronExpress)
    {
        return registSchedule(connectionUrl, serviceName, cronExpress, null, false);
    }

    public String registSchedule(String connectionUrl, String serviceName, String cronExpress, java.util.Map<String, String> __ctx)
    {
        return registSchedule(connectionUrl, serviceName, cronExpress, __ctx, true);
    }

    private String registSchedule(String connectionUrl, String serviceName, String cronExpress, java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        __checkTwowayOnly(__registSchedule_name);
        return end_registSchedule(begin_registSchedule(connectionUrl, serviceName, cronExpress, __ctx, __explicitCtx, true, null));
    }

    public Ice.AsyncResult begin_registSchedule(String connectionUrl, String serviceName, String cronExpress)
    {
        return begin_registSchedule(connectionUrl, serviceName, cronExpress, null, false, false, null);
    }

    public Ice.AsyncResult begin_registSchedule(String connectionUrl, String serviceName, String cronExpress, java.util.Map<String, String> __ctx)
    {
        return begin_registSchedule(connectionUrl, serviceName, cronExpress, __ctx, true, false, null);
    }

    public Ice.AsyncResult begin_registSchedule(String connectionUrl, String serviceName, String cronExpress, Ice.Callback __cb)
    {
        return begin_registSchedule(connectionUrl, serviceName, cronExpress, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_registSchedule(String connectionUrl, String serviceName, String cronExpress, java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_registSchedule(connectionUrl, serviceName, cronExpress, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_registSchedule(String connectionUrl, String serviceName, String cronExpress, Callback_ScheduleService_registSchedule __cb)
    {
        return begin_registSchedule(connectionUrl, serviceName, cronExpress, null, false, false, __cb);
    }

    public Ice.AsyncResult begin_registSchedule(String connectionUrl, String serviceName, String cronExpress, java.util.Map<String, String> __ctx, Callback_ScheduleService_registSchedule __cb)
    {
        return begin_registSchedule(connectionUrl, serviceName, cronExpress, __ctx, true, false, __cb);
    }

    public Ice.AsyncResult begin_registSchedule(String connectionUrl, 
                                                String serviceName, 
                                                String cronExpress, 
                                                IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_registSchedule(connectionUrl, serviceName, cronExpress, null, false, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_registSchedule(String connectionUrl, 
                                                String serviceName, 
                                                String cronExpress, 
                                                IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_registSchedule(connectionUrl, serviceName, cronExpress, null, false, false, __responseCb, __exceptionCb, __sentCb);
    }

    public Ice.AsyncResult begin_registSchedule(String connectionUrl, 
                                                String serviceName, 
                                                String cronExpress, 
                                                java.util.Map<String, String> __ctx, 
                                                IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb)
    {
        return begin_registSchedule(connectionUrl, serviceName, cronExpress, __ctx, true, false, __responseCb, __exceptionCb, null);
    }

    public Ice.AsyncResult begin_registSchedule(String connectionUrl, 
                                                String serviceName, 
                                                String cronExpress, 
                                                java.util.Map<String, String> __ctx, 
                                                IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_registSchedule(connectionUrl, serviceName, cronExpress, __ctx, true, false, __responseCb, __exceptionCb, __sentCb);
    }

    private Ice.AsyncResult begin_registSchedule(String connectionUrl, 
                                                 String serviceName, 
                                                 String cronExpress, 
                                                 java.util.Map<String, String> __ctx, 
                                                 boolean __explicitCtx, 
                                                 boolean __synchronous, 
                                                 IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                                 IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                                 IceInternal.Functional_BoolCallback __sentCb)
    {
        return begin_registSchedule(connectionUrl, serviceName, cronExpress, __ctx, __explicitCtx, __synchronous, 
                                    new IceInternal.Functional_TwowayCallbackArg1<String>(__responseCb, __exceptionCb, __sentCb)
                                        {
                                            public final void __completed(Ice.AsyncResult __result)
                                            {
                                                ScheduleServicePrxHelper.__registSchedule_completed(this, __result);
                                            }
                                        });
    }

    private Ice.AsyncResult begin_registSchedule(String connectionUrl, 
                                                 String serviceName, 
                                                 String cronExpress, 
                                                 java.util.Map<String, String> __ctx, 
                                                 boolean __explicitCtx, 
                                                 boolean __synchronous, 
                                                 IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__registSchedule_name);
        IceInternal.OutgoingAsync __result = getOutgoingAsync(__registSchedule_name, __cb);
        try
        {
            __result.prepare(__registSchedule_name, Ice.OperationMode.Normal, __ctx, __explicitCtx, __synchronous);
            IceInternal.BasicStream __os = __result.startWriteParams(Ice.FormatType.DefaultFormat);
            __os.writeString(connectionUrl);
            __os.writeString(serviceName);
            __os.writeString(cronExpress);
            __result.endWriteParams();
            __result.invoke();
        }
        catch(Ice.Exception __ex)
        {
            __result.abort(__ex);
        }
        return __result;
    }

    public String end_registSchedule(Ice.AsyncResult __iresult)
    {
        IceInternal.OutgoingAsync __result = IceInternal.OutgoingAsync.check(__iresult, this, __registSchedule_name);
        try
        {
            if(!__result.__wait())
            {
                try
                {
                    __result.throwUserException();
                }
                catch(Ice.UserException __ex)
                {
                    throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
                }
            }
            IceInternal.BasicStream __is = __result.startReadParams();
            String __ret;
            __ret = __is.readString();
            __result.endReadParams();
            return __ret;
        }
        finally
        {
            if(__result != null)
            {
                __result.cacheMessageBuffers();
            }
        }
    }

    static public void __registSchedule_completed(Ice.TwowayCallbackArg1<String> __cb, Ice.AsyncResult __result)
    {
        com.maomao.server.plugin.schedule.idl.ScheduleServicePrx __proxy = (com.maomao.server.plugin.schedule.idl.ScheduleServicePrx)__result.getProxy();
        String __ret = null;
        try
        {
            __ret = __proxy.end_registSchedule(__result);
        }
        catch(Ice.LocalException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        catch(Ice.SystemException __ex)
        {
            __cb.exception(__ex);
            return;
        }
        __cb.response(__ret);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static ScheduleServicePrx checkedCast(Ice.ObjectPrx __obj)
    {
        return checkedCastImpl(__obj, ice_staticId(), ScheduleServicePrx.class, ScheduleServicePrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @param __ctx The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static ScheduleServicePrx checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __ctx, ice_staticId(), ScheduleServicePrx.class, ScheduleServicePrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @param __facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static ScheduleServicePrx checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return checkedCastImpl(__obj, __facet, ice_staticId(), ScheduleServicePrx.class, ScheduleServicePrxHelper.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param __obj The untyped proxy.
     * @param __facet The name of the desired facet.
     * @param __ctx The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    public static ScheduleServicePrx checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        return checkedCastImpl(__obj, __facet, __ctx, ice_staticId(), ScheduleServicePrx.class, ScheduleServicePrxHelper.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param __obj The untyped proxy.
     * @return A proxy for this type.
     **/
    public static ScheduleServicePrx uncheckedCast(Ice.ObjectPrx __obj)
    {
        return uncheckedCastImpl(__obj, ScheduleServicePrx.class, ScheduleServicePrxHelper.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param __obj The untyped proxy.
     * @param __facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    public static ScheduleServicePrx uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        return uncheckedCastImpl(__obj, __facet, ScheduleServicePrx.class, ScheduleServicePrxHelper.class);
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::idl::ScheduleService"
    };

    /**
     * Provides the Slice type ID of this type.
     * @return The Slice type ID.
     **/
    public static String ice_staticId()
    {
        return __ids[1];
    }

    public static void __write(IceInternal.BasicStream __os, ScheduleServicePrx v)
    {
        __os.writeProxy(v);
    }

    public static ScheduleServicePrx __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            ScheduleServicePrxHelper result = new ScheduleServicePrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }

    public static final long serialVersionUID = 0L;
}
